<a href="https://colab.research.google.com/github/ibarra-fernando/Laboratorio-de-metodos-Cuantitativos-Aplicados-a-la-gestion/blob/main/notebooks/Practicas/practica_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Clase 1 - Introducción a Python para el manejo de datos organizacionales**

Ejemplo: ⏩ Problema de costos de fabricación

Las sillas requieren: 12 unidades de madera, 0.5 botellas de barniz, 6 horas/hombre
Los escritorios requieren: 25 unidades de madera, 2 botellas de barniz, 20 horas/hombre
Costos:

Madera: $6 por unidad

Barniz: $18 por botella

Mano de obra: $15 por hora

Calcular:

a) Costo unitario por cada artículo

b) Costo de elaborar 12 sillas y 20 escritorios

In [1]:
# Importamos numpy para operaciones numéricas

import numpy as np

In [ ]:
# Vector de requerimientos por unidad

requerimientos_sillas = np.array([12, 0.5, 6])
requerimientos_sillas

array([12. ,  0.5,  6. ])

In [ ]:
requerimientos_escritorios = np.array([25, 2, 20])
requerimientos_escritorios

array([25,  2, 20])

In [ ]:
# Vector de costos

costos = np.array([[6], [18], [15]])
costos

array([[ 6],
       [18],
       [15]])

In [ ]:
# Costo unitario de las sillas

costos_sillas = np.dot(requerimientos_sillas, costos)
costos_sillas

array([171.])

In [ ]:
# Costo unitario de los escritorios

costos_escritorios = np.dot(requerimientos_escritorios, costos)
costos_escritorios

array([486])

In [ ]:
# Calculamos el costo total de fabricar 12 sillas y 20 escritorios

costo_total = 12*costos_sillas + 20*costos_escritorios
print(f"\nCosto total de 12 sillas y 20 escritorios: ${costo_total[0]}")


Costo total de 12 sillas y 20 escritorios: $11772.0


Ejercicio: ⏩ Problema del transporte de petróleo

Una empresa petrolera debe transportar crudo a cuatro destilerías con las siguientes cantidades (m³) y costos ($/m³):

Destilería 1: 1000 m³ a $50

Destilería 2: 1550 m³ a $80

Destilería 3: 4580 m³ a $70

Destilería 4: 2350 m³ a $90

Calcular el costo total de transporte.

In [2]:
#Vector de cantidades
cantidades = np.array([1000, 1550, 4580, 2350])
cantidades

array([1000, 1550, 4580, 2350])

In [4]:
#Vector de costos
costos = np.array([[50], [80], [70], [90]])
costos

array([[50],
       [80],
       [70],
       [90]])

In [8]:
#Calculamos el costo total
costo_total = np.dot(cantidades, costos)
print(f"El costo total de transporte es: ${costo_total[0]}")

El costo total de transporte es: $706100


numpy.ndarray

Ejercicio: ⏩ Problema de costos de una panadería

Una panadería produce pan y pasteles

El pan requiere 5kg harina, 2h trabajo

Los pasteles requieren 3kg harina, 4h trabajo.

Los costos de materias primas son:

*harina $10/kg,

*trabajo $25/h.

Calcula el costo unitario de cada producto y el costo total para producir 30 panes y 15 pasteles.

In [10]:
# Armamos el vector requerimientos unitarios del pan
requerimientos_pan = np.array([5, 2])
requerimientos_pan

array([5, 2])

In [11]:
# Armamos el vector requerimientos unitarios del pastel
requerimientos_pastel = np.array([3, 4])
requerimientos_pastel

array([3, 4])

In [12]:
# Armamos el vector de costos de materias primas
costos = np.array([[10], [25]])
costos

array([[10],
       [25]])

In [14]:
# Calculamos el costo unitario del pan
costo_unitario_pan = np.dot(requerimientos_pan, costos)
costo_unitario_pan

array([100])

In [15]:
# Calculamos el costo unitario del pastel
costo_unitario_pastel = np.dot(requerimientos_pastel, costos)
costo_unitario_pastel

array([130])

In [16]:
# Calculamos el costo de fabricar 30 panes y 15 pasteles
costo_total = 30 * costo_unitario_pan + 15 * costo_unitario_pastel
print(f"El costo total de fabricar 30 panes y 15 pasteles es: ${costo_total[0]}")

El costo total de fabricar 30 panes y 15 pasteles es: $4950
