<a href="https://colab.research.google.com/github/ibarra-fernando/Laboratorio-de-metodos-Cuantitativos-Aplicados-a-la-gestion/blob/main/notebooks/Practicas/practica_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Clase 1 - Introducción a Python para el manejo de datos organizacionales**

Ejemplo:

Un fabricante produce sillas y escritorios:

Las sillas requieren: 12 unidades de madera, 0.5 botellas de barniz, 6 horas/hombre
Los escritorios requieren: 25 unidades de madera, 2 botellas de barniz, 20 horas/hombre
Costos:

Madera: $6 por unidad

Barniz: $18 por botella

Mano de obra: $15 por hora

Calcular:

a) Costo unitario por cada artículo

b) Costo de elaborar 12 sillas y 20 escritorios

In [1]:
# Importamos numpy para operaciones numéricas

import numpy as np

In [4]:
# Vector de requerimientos por unidad

requerimientos_sillas = np.array([12, 0.5, 6])
requerimientos_sillas

array([12. ,  0.5,  6. ])

In [6]:
requerimientos_escritorios = np.array([25, 2, 20])
requerimientos_escritorios

array([25,  2, 20])

In [10]:
# Vector de costos

costos = np.array([[6], [18], [15]])
costos

array([[ 6],
       [18],
       [15]])

In [11]:
# Costo unitario de las sillas

costos_sillas = np.dot(requerimientos_sillas, costos)
costos_sillas

array([171.])

In [12]:
# Costo unitario de los escritorios

costos_escritorios = np.dot(requerimientos_escritorios, costos)
costos_escritorios

array([486])

In [17]:
# Calculamos el costo total de fabricar 12 sillas y 20 escritorios

costo_total = 12*costos_sillas + 20*costos_escritorios
print(f"\nCosto total de 12 sillas y 20 escritorios: ${costo_total[0]}")


Costo total de 12 sillas y 20 escritorios: $11772.0
